// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6iCCLuz1lxzaCoyL128QwrZTtHWxO2Q',
    appId: '1:587832712055:android:6ef634f817d7bf74b09f72',
    messagingSenderId: '587832712055',
    projectId: 'doctor-3778f',
    storageBucket: 'doctor-3778f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHm7ARUu9qCCvkuB4b3DXw3Wr8nQN5T4',
    appId: '1:587832712055:ios:200da14743ba741db09f72',
    messagingSenderId: '587832712055',
    projectId: 'doctor-3778f',
    storageBucket: 'doctor-3778f.appspot.com',
    iosClientId: '587832712055-ennkbnf950qk8o5i26rdldfneh9910rt.apps.googleusercontent.com',
    iosBundleId: 'com.htidoctor.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHm7ARUu9qCCvkuB4b3DXw3Wr8nQN5T4',
    appId: '1:587832712055:ios:200da14743ba741db09f72',
    messagingSenderId: '587832712055',
    projectId: 'doctor-3778f',
    storageBucket: 'doctor-3778f.appspot.com',
    iosClientId: '587832712055-ennkbnf950qk8o5i26rdldfneh9910rt.apps.googleusercontent.com',
    iosBundleId: 'com.htidoctor.doctor',
  );
}
